### ISSUE TITLE
Java Error: Caused by: java.lang.ClassCastException

### ISSUE THREAD

**Issue by JDittmerCOM** [Minecraft-Eternal/MC-Eternal-1.12#19]
Hi, I always get the same error message the first time I start the server.
How does this come about? 

```
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more
```

**Comment by anabsolutesloth** [comment]
Appears that this is a Java-related error, specifically that your Java is too new for Minecraft 1.12.
https://www.java.com/en/download/manual.jsp
Get java 1.8.0_281 from the proper download link for your system's OS and install it.

**Comment by JDittmerCOM** [comment]
All right, thanks for the quick response.
I already thought that my Java is too new for it.
